### ISSUE TITLE
Add jQuery JS for Navbar to use routes defined in handlebars.controller file

### ISSUE THREAD

**Issue by kjknudtson** [dbreznay/Daring-Donkeys#37]

**Comment by dbreznay** [comment]
having issues with routes. cannot get pages to render properly

**Comment by dbreznay** [comment]
$('.navbar navbar-expand-lg navbar-light bg-light').on('click','div', function(){
    $('.navbar navbar-expand-lg navbar-light bg-light div.active').removeClass('active');
    $(this).addClass('active');  
`});```
